version: '3.8'



services:

  app:

    image: mostafamohamedelsaht/lab8-app:latest   # تأكد من هذا الاسم بدقة
    container_name: lab-app

    ports:

      - "3000:3000"

    environment:

      - MONGO_URL=mongodb://mongo:27017/lab8

    depends_on:

      - mongo

    networks:

      - lab8-net



  mongo:

    image: mongo:latest

    container_name: mongo

    restart: always

    volumes:

      - mongo-data:/data/db

    networks:

      - lab8-net



networks:

  lab8-net:



volumes:

  mongo-data: